export const publicRoutes = [
  "/",
  "/en",
  "/de",
  "/en/features",
  "/de/features",
  "/en/pricing",
  "/de/pricing",
  "/en/templates",
  "/de/templates",
  "/en/contact",
  "/de/contact",
  "/en/sign-in",
  "/de/sign-in",
  "/en/register",
  "/de/register",
  "/en/forgot-password",
  "/de/forgot-password",
  "/en/verify-otp",
  "/de/verify-otp",
  "/en/reset-password",
  "/de/reset-password",
  "/en/email-verified",
  "/de/email-verified",
  "/en/privacy",
  "/de/privacy",
  "/en/terms",
  "/de/terms",
  "/en/cookies",
  "/de/cookies",
  "/en/faq",
  "/de/faq",
  "/en/careers",
  "/de/careers",
  "/en/recruiter-builder",
  "/de/recruiter-builder",
] as const;

export const authRoutes = [
  "/en/sign-in",
  "/de/sign-in",
  "/en/register",
  "/de/register",
  "/en/forgot-password",
  "/de/forgot-password",
  "/en/verify-otp",
  "/de/verify-otp",
  "/en/reset-password",
  "/de/reset-password",
  "/en/email-verified",
  "/de/email-verified",
] as const;

export const protectedRoutePrefixes = [
  "/en/dashboard",
  "/de/dashboard",
  "/en/profile",
  "/de/profile",
  "/en/settings",
  "/de/settings",
] as const;
