/** ATS-relevant keywords for MERN/PERN and German tech hiring */
export const ATS_KEYWORDS = [
  "react",
  "next.js",
  "nextjs",
  "node",
  "nodejs",
  "typescript",
  "javascript",
  "postgresql",
  "postgres",
  "mongodb",
  "express",
  "nestjs",
  "docker",
  "aws",
  "vercel",
  "railway",
  "git",
  "github",
  "rest",
  "api",
  "jwt",
  "stripe",
  "tailwind",
  "redux",
  "redis",
  "ci/cd",
  "agile",
  "typescript",
] as const;

export const ACTION_VERBS = [
  "developed",
  "built",
  "implemented",
  "designed",
  "led",
  "improved",
  "optimized",
  "architected",
  "integrated",
  "deployed",
  "entwickelt",
  "implementiert",
  "optimiert",
] as const;

export const METRIC_PATTERN = /\d+%|\d+\+|\d+k|\d+M|€|\$|\d+\s*(users|Kunden|requests|ms)/i;
